### ISSUE TITLE
I am lil bit lost what these are doing here :see_no_evil:

### ISSUE THREAD

**Issue by thapakazi** [prabes/Ansible-Scripts#10]
https://github.com/prabes/Ansible-Scripts/blob/57caaec9c4030c0c5a59dfedc93e83bccbbfd502/deploy-wordpress-with-Ansible/roles/mySQL/handlers/main.yml#L6-L9

**Comment by prabes** [comment]
Hmm. A noob mistake you caught me on.
A lot of `main.yml` got to look at once. :laughing:

**Comment by thapakazi** [comment]
go one by one, make  a single role functional first.

**Comment by prabes** [comment]
@thapakazi 
It's addressed over this [commit](https://github.com/prabes/Ansible-Scripts/commit/987fa99780ae90ce2f39cc602d5b4c649b42edf3)
