### ISSUE TITLE
[Refactor]: make it generic

### ISSUE THREAD

**Issue by thapakazi** [prabes/Ansible-Scripts#2]
https://github.com/prabes/Ansible-Scripts/blob/9968cd31c3bf13ffd0b186555752824925dda437/deploy-wordpress-with-Ansible/env_setup.yml#L74

**Comment by prabes** [comment]
@thapakazi Please review the changes dai.
I have commited the changes addressing all the issues.
https://github.com/prabes/Ansible-Scripts/commit/ac41842e4524a309be5a9611af0e658f6d03da37

**Comment by thapakazi** [comment]
ok brother
