### ISSUE TITLE
LOL: resolve finished issues and add README

### ISSUE THREAD

**Issue by thapakazi** [prabes/Ansible-Scripts#7]
Please comment and close old issues,  though you have covered them, its always nice to drop a comment and close them properly.

And add Readme.md file on root of repo, it will help explain about your project.

**Comment by prabes** [comment]
Yeah. Okay Dai. Sure :smile:
README Comming so soon.

**Comment by prabes** [comment]
Initiated this. Lot of room left to improve though.
