### ISSUE TITLE
[improvements] these looks like installing some pkg, can we put them together ?

### ISSUE THREAD

**Issue by thapakazi** [prabes/Ansible-Scripts#9]
https://github.com/prabes/Ansible-Scripts/blob/57caaec9c4030c0c5a59dfedc93e83bccbbfd502/deploy-wordpress-with-Ansible/roles/common/tasks/main.yml#L2-L13

**Comment by prabes** [comment]
Yeah. We can do that.

**Comment by thapakazi** [comment]
BTW, I like the idea of separating out a common role :+1:

**Comment by prabes** [comment]
May not be applicable in this particular scene. 
But Yeah. I found it useful.

**Comment by prabes** [comment]
New changes has been made:
* The Role `common` have been removed 
* Tasks on `common` role has been included under role `PHPpackages`   
[Check Diff Here](https://github.com/prabes/Ansible-Scripts/commit/987fa99780ae90ce2f39cc602d5b4c649b42edf3)
